export interface EmojiAsset {
  id: string;
  name: string;
  unicode: string;
  shortcode: string;
  category: string;
}

export const EMOJI_CATEGORIES = [
  { id: 'smileys', label: 'Smileys', icon: '😊' },
  { id: 'people', label: 'People', icon: '👋' },
  { id: 'animals', label: 'Nature', icon: '🐶' },
  { id: 'food', label: 'Food', icon: '🍎' },
  { id: 'activities', label: 'Activities', icon: '⚽' },
  { id: 'travel', label: 'Travel', icon: '✈️' },
  { id: 'objects', label: 'Objects', icon: '💡' },
  { id: 'symbols', label: 'Symbols', icon: '🔣' },
  { id: 'flags', label: 'Flags', icon: '🏁' },
];

export const ALL_EMOJIS: EmojiAsset[] = [
  // SMILEYS
  { id: '1f600', name: 'Grinning Face', unicode: '1f600', shortcode: ':smile:', category: 'smileys' },
  { id: '1f603', name: 'Grinning Face with Big Eyes', unicode: '1f603', shortcode: ':smiley:', category: 'smileys' },
  { id: '1f604', name: 'Grinning Face with Smiling Eyes', unicode: '1f604', shortcode: ':laughing:', category: 'smileys' },
  { id: '1f601', name: 'Beaming Face with Smiling Eyes', unicode: '1f601', shortcode: ':grin:', category: 'smileys' },
  { id: '1f606', name: 'Squinting Face with Tongue', unicode: '1f606', shortcode: ':stuck_out_tongue_closed_eyes:', category: 'smileys' },
  { id: '1f605', name: 'Grinning Face with Sweat', unicode: '1f605', shortcode: ':sweat_smile:', category: 'smileys' },
  { id: '1f923', name: 'Rolling on the Floor Laughing', unicode: '1f923', shortcode: ':rofl:', category: 'smileys' },
  { id: '1f602', name: 'Face with Tears of Joy', unicode: '1f602', shortcode: ':joy:', category: 'smileys' },
  { id: '1f642', name: 'Slightly Smiling Face', unicode: '1f642', shortcode: ':slight_smile:', category: 'smileys' },
  { id: '1f643', name: 'Upside-Down Face', unicode: '1f643', shortcode: ':upside_down_face:', category: 'smileys' },
  { id: '1f609', name: 'Winking Face', unicode: '1f609', shortcode: ':wink:', category: 'smileys' },
  { id: '1f60a', name: 'Smiling Face with Smiling Eyes', unicode: '1f60a', shortcode: ':blush:', category: 'smileys' },
  { id: '1f607', name: 'Smiling Face with Halo', unicode: '1f607', shortcode: ':innocent:', category: 'smileys' },
  { id: '1f970', name: 'Smiling Face with Hearts', unicode: '1f970', shortcode: ':smiling_face_with_3_hearts:', category: 'smileys' },
  { id: '1f60d', name: 'Smiling Face with Heart-Eyes', unicode: '1f60d', shortcode: ':heart_eyes:', category: 'smileys' },
  { id: '1f929', name: 'Star-Struck', unicode: '1f929', shortcode: ':star_struck:', category: 'smileys' },
  { id: '1f618', name: 'Face Blowing a Kiss', unicode: '1f618', shortcode: ':kissing_heart:', category: 'smileys' },
  { id: '1f617', name: 'Kissing Face', unicode: '1f617', shortcode: ':kissing:', category: 'smileys' },
  { id: '1f61a', name: 'Kissing Face with Closed Eyes', unicode: '1f61a', shortcode: ':kissing_closed_eyes:', category: 'smileys' },
  { id: '1f619', name: 'Kissing Face with Smiling Eyes', unicode: '1f619', shortcode: ':kissing_smiling_eyes:', category: 'smileys' },
  { id: '1f60b', name: 'Face Savoring Food', unicode: '1f60b', shortcode: ':yum:', category: 'smileys' },
  { id: '1f61b', name: 'Face with Tongue', unicode: '1f61b', shortcode: ':stuck_out_tongue:', category: 'smileys' },
  { id: '1f61c', name: 'Winking Face with Tongue', unicode: '1f61c', shortcode: ':stuck_out_tongue_winking_eye:', category: 'smileys' },
  { id: '1f92a', name: 'Zany Face', unicode: '1f92a', shortcode: ':zany_face:', category: 'smileys' },
  { id: '1f61d', name: 'Squinting Face with Tongue', unicode: '1f61d', shortcode: ':stuck_out_tongue_closed_eyes:', category: 'smileys' },
  { id: '1f911', name: 'Money-Mouth Face', unicode: '1f911', shortcode: ':money_mouth_face:', category: 'smileys' },
  { id: '1f917', name: 'Hugging Face', unicode: '1f917', shortcode: ':hugs:', category: 'smileys' },
  { id: '1f92d', name: 'Face with Hand Over Mouth', unicode: '1f92d', shortcode: ':hand_over_mouth:', category: 'smileys' },
  { id: '1f92b', name: 'Shushing Face', unicode: '1f92b', shortcode: ':shushing_face:', category: 'smileys' },
  { id: '1f914', name: 'Thinking Face', unicode: '1f914', shortcode: ':thinking:', category: 'smileys' },
  { id: '1f910', name: 'Zipper-Mouth Face', unicode: '1f910', shortcode: ':zipper_mouth_face:', category: 'smileys' },
  { id: '1f928', name: 'Face with Raised Eyebrow', unicode: '1f928', shortcode: ':raised_eyebrow:', category: 'smileys' },
  { id: '1f610', name: 'Neutral Face', unicode: '1f610', shortcode: ':neutral_face:', category: 'smileys' },
  { id: '1f611', name: 'Expressionless Face', unicode: '1f611', shortcode: ':expressionless:', category: 'smileys' },
  { id: '1f636', name: 'Face Without Mouth', unicode: '1f636', shortcode: ':no_mouth:', category: 'smileys' },
  { id: '1f60f', name: 'Smirking Face', unicode: '1f60f', shortcode: ':smirk:', category: 'smileys' },
  { id: '1f612', name: 'Unamused Face', unicode: '1f612', shortcode: ':unamused:', category: 'smileys' },
  { id: '1f644', name: 'Face with Rolling Eyes', unicode: '1f644', shortcode: ':roll_eyes:', category: 'smileys' },
  { id: '1f62c', name: 'Grimacing Face', unicode: '1f62c', shortcode: ':grimacing:', category: 'smileys' },
  { id: '1f925', name: 'Lying Face', unicode: '1f925', shortcode: ':lying_face:', category: 'smileys' },
  { id: '1f60c', name: 'Relieved Face', unicode: '1f60c', shortcode: ':relieved:', category: 'smileys' },
  { id: '1f614', name: 'Pensive Face', unicode: '1f614', shortcode: ':pensive:', category: 'smileys' },
  { id: '1f62a', name: 'Sleepy Face', unicode: '1f62a', shortcode: ':sleepy:', category: 'smileys' },
  { id: '1f634', name: 'Sleeping Face', unicode: '1f634', shortcode: ':sleeping:', category: 'smileys' },
  { id: '1f637', name: 'Face with Medical Mask', unicode: '1f637', shortcode: ':mask:', category: 'smileys' },
  { id: '1f912', name: 'Face with Thermometer', unicode: '1f912', shortcode: ':face_with_thermometer:', category: 'smileys' },
  { id: '1f915', name: 'Face with Head-Bandage', unicode: '1f915', shortcode: ':face_with_head_bandage:', category: 'smileys' },
  { id: '1f922', name: 'Nauseated Face', unicode: '1f922', shortcode: ':nauseated_face:', category: 'smileys' },
  { id: '1f92e', name: 'Face Vomiting', unicode: '1f92e', shortcode: ':face_vomiting:', category: 'smileys' },
  { id: '1f927', name: 'Sneezing Face', unicode: '1f927', shortcode: ':sneezing_face:', category: 'smileys' },
  { id: '1f975', name: 'Hot Face', unicode: '1f975', shortcode: ':hot_face:', category: 'smileys' },
  { id: '1f976', name: 'Cold Face', unicode: '1f976', shortcode: ':cold_face:', category: 'smileys' },
  { id: '1f974', name: 'Woozy Face', unicode: '1f974', shortcode: ':woozy_face:', category: 'smileys' },
  { id: '1f635', name: 'Knock-out Face', unicode: '1f635', shortcode: ':dizzy_face:', category: 'smileys' },
  { id: '1f92f', name: 'Exploding Head', unicode: '1f92f', shortcode: ':exploding_head:', category: 'smileys' },
  { id: '1f60e', name: 'Smiling Face with Sunglasses', unicode: '1f60e', shortcode: ':sunglasses:', category: 'smileys' },
  { id: '1f913', name: 'Nerd Face', unicode: '1f913', shortcode: ':nerd_face:', category: 'smileys' },
  { id: '1f9d0', name: 'Face with Monocle', unicode: '1f9d0', shortcode: ':monocle_face:', category: 'smileys' },
  { id: '1f615', name: 'Confused Face', unicode: '1f615', shortcode: ':confused:', category: 'smileys' },
  { id: '1f61f', name: 'Worried Face', unicode: '1f61f', shortcode: ':worried:', category: 'smileys' },
  { id: '1f641', name: 'Slightly Frowning Face', unicode: '1f641', shortcode: ':slight_frown:', category: 'smileys' },
  { id: '2639', name: 'Frowning Face', unicode: '2639', shortcode: ':frowning_face:', category: 'smileys' },
  { id: '1f62e', name: 'Face with Open Mouth', unicode: '1f62e', shortcode: ':open_mouth:', category: 'smileys' },
  { id: '1f62f', name: 'Hushed Face', unicode: '1f62f', shortcode: ':hushed:', category: 'smileys' },
  { id: '1f632', name: 'Astonished Face', unicode: '1f632', shortcode: ':astonished:', category: 'smileys' },
  { id: '1f633', name: 'Flushed Face', unicode: '1f633', shortcode: ':flushed:', category: 'smileys' },
  { id: '1f97a', name: 'Pleading Face', unicode: '1f97a', shortcode: ':pleading_face:', category: 'smileys' },
  { id: '1f626', name: 'Frowning Face with Open Mouth', unicode: '1f626', shortcode: ':frowning:', category: 'smileys' },
  { id: '1f627', name: 'Anguished Face', unicode: '1f627', shortcode: ':anguished:', category: 'smileys' },
  { id: '1f628', name: 'Fearful Face', unicode: '1f628', shortcode: ':fearful:', category: 'smileys' },
  { id: '1f630', name: 'Cold Sweat Face', unicode: '1f630', shortcode: ':cold_sweat:', category: 'smileys' },
  { id: '1f625', name: 'Sad but Relieved Face', unicode: '1f625', shortcode: ':disappointed_relieved:', category: 'smileys' },
  { id: '1f622', name: 'Crying Face', unicode: '1f622', shortcode: ':cry:', category: 'smileys' },
  { id: '1f62d', name: 'Loudly Crying Face', unicode: '1f62d', shortcode: ':sob:', category: 'smileys' },
  { id: '1f631', name: 'Face Screaming in Fear', unicode: '1f631', shortcode: ':scream:', category: 'smileys' },
  { id: '1f616', name: 'Confounded Face', unicode: '1f616', shortcode: ':confounded:', category: 'smileys' },
  { id: '1f623', name: 'Persevering Face', unicode: '1f623', shortcode: ':persevere:', category: 'smileys' },
  { id: '1f61e', name: 'Disappointed Face', unicode: '1f61e', shortcode: ':disappointed:', category: 'smileys' },
  { id: '1f613', name: 'Face with Sweat', unicode: '1f613', shortcode: ':sweat:', category: 'smileys' },
  { id: '1f629', name: 'Weary Face', unicode: '1f629', shortcode: ':weary:', category: 'smileys' },
  { id: '1f62b', name: 'Tired Face', unicode: '1f62b', shortcode: ':tired_face:', category: 'smileys' },
  { id: '1f971', name: 'Yawning Face', unicode: '1f971', shortcode: ':yawning_face:', category: 'smileys' },
  { id: '1f624', name: 'Face with Steam From Nose', unicode: '1f624', shortcode: ':triumph:', category: 'smileys' },
  { id: '1f621', name: 'Pouting Face', unicode: '1f621', shortcode: ':rage:', category: 'smileys' },
  { id: '1f620', name: 'Angry Face', unicode: '1f620', shortcode: ':angry:', category: 'smileys' },
  { id: '1f92c', name: 'Face with Symbols on Mouth', unicode: '1f92c', shortcode: ':cursing_face:', category: 'smileys' },
  
  // PEOPLE
  { id: '1f44b', name: 'Waving Hand', unicode: '1f44b', shortcode: ':wave:', category: 'people' },
  { id: '1f91a', name: 'Raised Back of Hand', unicode: '1f91a', shortcode: ':raised_back_of_hand:', category: 'people' },
  { id: '1f590', name: 'Hand with Fingers Splayed', unicode: '1f590', shortcode: ':raised_hand_with_fingers_splayed:', category: 'people' },
  { id: '270b', name: 'Raised Hand', unicode: '270b', shortcode: ':raised_hand:', category: 'people' },
  { id: '1f596', name: 'Vulcan Salute', unicode: '1f596', shortcode: ':vulcan_salute:', category: 'people' },
  { id: '1f44c', name: 'OK Hand', unicode: '1f44c', shortcode: ':ok_hand:', category: 'people' },
  { id: '1f90f', name: 'Pinching Hand', unicode: '1f90f', shortcode: ':pinching_hand:', category: 'people' },
  { id: '270c', name: 'Victory Hand', unicode: '270c', shortcode: ':v:', category: 'people' },
  { id: '1f91e', name: 'Crossed Fingers', unicode: '1f91e', shortcode: ':crossed_fingers:', category: 'people' },
  { id: '1f91f', name: 'Love-You Gesture', unicode: '1f91f', shortcode: ':love_you_gesture:', category: 'people' },
  { id: '1f918', name: 'Sign of the Horns', unicode: '1f918', shortcode: ':the_horns:', category: 'people' },
  { id: '1f919', name: 'Call Me Hand', unicode: '1f919', shortcode: ':call_me_hand:', category: 'people' },
  { id: '1f448', name: 'Backhand Index Pointing Left', unicode: '1f448', shortcode: ':point_left:', category: 'people' },
  { id: '1f449', name: 'Backhand Index Pointing Right', unicode: '1f449', shortcode: ':point_right:', category: 'people' },
  { id: '1f446', name: 'Backhand Index Pointing Up', unicode: '1f446', shortcode: ':point_up_2:', category: 'people' },
  { id: '1f595', name: 'Middle Finger', unicode: '1f595', shortcode: ':middle_finger:', category: 'people' },
  { id: '1f447', name: 'Backhand Index Pointing Down', unicode: '1f447', shortcode: ':point_down:', category: 'people' },
  { id: '261d', name: 'Index Pointing Up', unicode: '261d', shortcode: ':point_up:', category: 'people' },
  { id: '1f44d', name: 'Thumbs Up', unicode: '1f44d', shortcode: ':thumbsup:', category: 'people' },
  { id: '1f44e', name: 'Thumbs Down', unicode: '1f44e', shortcode: ':thumbsdown:', category: 'people' },
  { id: '270a', name: 'Raised Fist', unicode: '270a', shortcode: ':fist:', category: 'people' },
  { id: '1f44a', name: 'Oncoming Fist', unicode: '1f44a', shortcode: ':facepunch:', category: 'people' },
  { id: '1f91b', name: 'Left-Facing Fist', unicode: '1f91b', shortcode: ':left-facing_fist:', category: 'people' },
  { id: '1f91c', name: 'Right-Facing Fist', unicode: '1f91c', shortcode: ':right-facing_fist:', category: 'people' },
  { id: '1f44f', name: 'Clapping Hands', unicode: '1f44f', shortcode: ':clap:', category: 'people' },
  { id: '1f64c', name: 'Raising Hands', unicode: '1f64c', shortcode: ':raised_hands:', category: 'people' },
  { id: '1f450', name: 'Open Hands', unicode: '1f450', shortcode: ':open_hands:', category: 'people' },
  { id: '1f932', name: 'Palms Up Together', unicode: '1f932', shortcode: ':palms_up_together:', category: 'people' },
  { id: '1f91d', name: 'Handshake', unicode: '1f91d', shortcode: ':handshake:', category: 'people' },
  { id: '1f64f', name: 'Folded Hands', unicode: '1f64f', shortcode: ':pray:', category: 'people' },
  { id: '270d', name: 'Writing Hand', unicode: '270d', shortcode: ':writing_hand:', category: 'people' },
  { id: '1f485', name: 'Nail Polish', unicode: '1f485', shortcode: ':nail_care:', category: 'people' },
  { id: '1f933', name: 'Selfie', unicode: '1f933', shortcode: ':selfie:', category: 'people' },
  { id: '1f4aa', name: 'Flexed Biceps', unicode: '1f4aa', shortcode: ':muscle:', category: 'people' },
  { id: '1f9be', name: 'Mechanical Arm', unicode: '1f9be', shortcode: ':mechanical_arm:', category: 'people' },
  { id: '1f9bf', name: 'Mechanical Leg', unicode: '1f9bf', shortcode: ':mechanical_leg:', category: 'people' },
  { id: '1f9b5', name: 'Leg', unicode: '1f9b5', shortcode: ':leg:', category: 'people' },
  { id: '1f9b6', name: 'Foot', unicode: '1f9b6', shortcode: ':foot:', category: 'people' },
  { id: '1f442', name: 'Ear', unicode: '1f442', shortcode: ':ear:', category: 'people' },
  { id: '1f9bb', name: 'Ear with Hearing Aid', unicode: '1f9bb', shortcode: ':ear_with_hearing_aid:', category: 'people' },
  { id: '1f443', name: 'Nose', unicode: '1f443', shortcode: ':nose:', category: 'people' },
  { id: '1f9e0', name: 'Brain', unicode: '1f9e0', shortcode: ':brain:', category: 'people' },
  { id: '1f9b7', name: 'Tooth', unicode: '1f9b7', shortcode: ':tooth:', category: 'people' },
  { id: '1f9b4', name: 'Bone', unicode: '1f9b4', shortcode: ':bone:', category: 'people' },
  { id: '1f440', name: 'Eyes', unicode: '1f440', shortcode: ':eyes:', category: 'people' },
  { id: '1f441', name: 'Eye', unicode: '1f441', shortcode: ':eye:', category: 'people' },
  { id: '1f445', name: 'Tongue', unicode: '1f445', shortcode: ':tongue:', category: 'people' },
  { id: '1f444', name: 'Mouth', unicode: '1f444', shortcode: ':lips:', category: 'people' },

  // ANIMALS
  { id: '1f435', name: 'Monkey Face', unicode: '1f435', shortcode: ':monkey_face:', category: 'animals' },
  { id: '1f412', name: 'Monkey', unicode: '1f412', shortcode: ':monkey:', category: 'animals' },
  { id: '1f436', name: 'Dog Face', unicode: '1f436', shortcode: ':dog:', category: 'animals' },
  { id: '1f415', name: 'Dog', unicode: '1f415', shortcode: ':dog2:', category: 'animals' },
  { id: '1f9ae', name: 'Sloth', unicode: '1f9ae', shortcode: ':sloth:', category: 'animals' },
  { id: '1f431', name: 'Cat Face', unicode: '1f431', shortcode: ':cat:', category: 'animals' },
  { id: '1f408', name: 'Cat', unicode: '1f408', shortcode: ':cat2:', category: 'animals' },
  { id: '1f981', name: 'Lion', unicode: '1f981', shortcode: ':lion:', category: 'animals' },
  { id: '1f42f', name: 'Tiger Face', unicode: '1f42f', shortcode: ':tiger:', category: 'animals' },
  { id: '1f42e', name: 'Cow Face', unicode: '1f42e', shortcode: ':cow:', category: 'animals' },
  { id: '1f437', name: 'Pig Face', unicode: '1f437', shortcode: ':pig:', category: 'animals' },
  { id: '1f43b', name: 'Bear Face', unicode: '1f43b', shortcode: ':bear:', category: 'animals' },
  { id: '1f43c', name: 'Panda Face', unicode: '1f43c', shortcode: ':panda_face:', category: 'animals' },
  { id: '1f42d', name: 'Mouse Face', unicode: '1f42d', shortcode: ':mouse:', category: 'animals' },
  { id: '1f430', name: 'Rabbit Face', unicode: '1f430', shortcode: ':rabbit:', category: 'animals' },
  { id: '1f438', name: 'Frog Face', unicode: '1f438', shortcode: ':frog:', category: 'animals' },
  { id: '1f40d', name: 'Snake', unicode: '1f40d', shortcode: ':snake:', category: 'animals' },
  { id: '1f432', name: 'Dragon Face', unicode: '1f432', shortcode: ':dragon_face:', category: 'animals' },
  { id: '1f996', name: 'T-Rex', unicode: '1f996', shortcode: ':t-rex:', category: 'animals' },
  { id: '1f42🐳', name: 'Spouting Whale', unicode: '1f433', shortcode: ':whale:', category: 'animals' },
  { id: '1f419', name: 'Octopus', unicode: '1f419', shortcode: ':octopus:', category: 'animals' },

  // FLAGS
  { id: '1f3c1', name: 'Chequered Flag', unicode: '1f3c1', shortcode: ':checkered_flag:', category: 'flags' },
  { id: '1f6a9', name: 'Triangular Flag', unicode: '1f6a9', shortcode: ':triangular_flag_on_post:', category: 'flags' },
  { id: '1f3f3-fe0f-200d-1f308', name: 'Rainbow Flag', unicode: '1f3f3-200d-1f308', shortcode: ':rainbow_flag:', category: 'flags' },
  { id: '1f3f4-200d-2620-fe0f', name: 'Pirate Flag', unicode: '1f3f4-200d-2620', shortcode: ':pirate_flag:', category: 'flags' },
  { id: '1f1e6-1f1f1', name: 'Albania', unicode: '1f1e6-1f1f1', shortcode: ':al:', category: 'flags' },
  { id: '1f1e6-1f1ec', name: 'Algeria', unicode: '1f1e6-1f1ec', shortcode: ':dz:', category: 'flags' },
  { id: '1f1e6-1f1f4', name: 'American Samoa', unicode: '1f1e6-1f1f4', shortcode: ':as:', category: 'flags' },
  { id: '1f1e6-1f1e9', name: 'Andorra', unicode: '1f1e6-1f1e9', shortcode: ':ad:', category: 'flags' },
  { id: '1f1e6-1f1f4', name: 'Angola', unicode: '1f1e6-1f1f4', shortcode: ':ao:', category: 'flags' },
  { id: '1f1e6-1f1f1', name: 'Anguilla', unicode: '1f1e6-1f1f1', shortcode: ':ai:', category: 'flags' },
  { id: '1f1e6-1f1f6', name: 'Antarctica', unicode: '1f1e6-1f1f6', shortcode: ':aq:', category: 'flags' },
  { id: '1f1e6-1f1f7', name: 'Argentina', unicode: '1f1e6-1f1f7', shortcode: ':ar:', category: 'flags' },
  { id: '1f1e6-1f1f2', name: 'Armenia', unicode: '1f1e6-1f1f2', shortcode: ':am:', category: 'flags' },
  { id: '1f1e6-1f1fc', name: 'Aruba', unicode: '1f1e6-1f1fc', shortcode: ':aw:', category: 'flags' },
  { id: '1f1e6-1f1fa', name: 'Australia', unicode: '1f1e6-1f1fa', shortcode: ':au:', category: 'flags' },
  { id: '1f1e6-1f1f9', name: 'Austria', unicode: '1f1e6-1f1f9', shortcode: ':at:', category: 'flags' },
  { id: '1f1e6-1f1ff', name: 'Azerbaijan', unicode: '1f1e6-1f1ff', shortcode: ':az:', category: 'flags' },
  { id: '1f1e7-1f1f8', name: 'Bahamas', unicode: '1f1e7-1f1f8', shortcode: ':bs:', category: 'flags' },
  { id: '1f1e7-1f1ded', name: 'Bahrain', unicode: '1f1e7-1f1ded', shortcode: ':bh:', category: 'flags' },
  { id: '1f1e7-1f1e9', name: 'Bangladesh', unicode: '1f1e7-1f1e9', shortcode: ':bd:', category: 'flags' },
  { id: '1f1e7-1f1f7', name: 'Barbados', unicode: '1f1e7-1f1f7', shortcode: ':bb:', category: 'flags' },
  { id: '1f1e7-1f1fe', name: 'Belarus', unicode: '1f1e7-1f1fe', shortcode: ':by:', category: 'flags' },
  { id: '1f1e7-1f1ea', name: 'Belgium', unicode: '1f1e7-1f1ea', shortcode: ':be:', category: 'flags' },
  { id: '1f1e7-1f1ff', name: 'Belize', unicode: '1f1e7-1f1ff', shortcode: ':bz:', category: 'flags' },
  { id: '1f1e7-1f1ef', name: 'Benin', unicode: '1f1e7-1f1ef', shortcode: ':bj:', category: 'flags' },
  { id: '1f1e7-1f1f2', name: 'Bermuda', unicode: '1f1e7-1f1f2', shortcode: ':bm:', category: 'flags' },
  { id: '1f1e7-1f1f9', name: 'Bhutan', unicode: '1f1e7-1f1f9', shortcode: ':bt:', category: 'flags' },
  { id: '1f1e7-1f1f4', name: 'Bolivia', unicode: '1f1e7-1f1f4', shortcode: ':bo:', category: 'flags' },
  { id: '1f1e7-1f1e6', name: 'Bosnia & Herzegovina', unicode: '1f1e7-1f1e6', shortcode: ':ba:', category: 'flags' },
  { id: '1f1e7-1f1fc', name: 'Botswana', unicode: '1f1e7-1f1fc', shortcode: ':bw:', category: 'flags' },
  { id: '1f1e7-1f1f7', name: 'Brazil', unicode: '1f1e7-1f1f7', shortcode: ':br:', category: 'flags' },
  { id: '1f1e7-1f1f3', name: 'Bulgaria', unicode: '1f1e7-1f1f3', shortcode: ':bg:', category: 'flags' },
  { id: '1f1e6-1f1f9', name: 'Canada', unicode: '1f1e8-1f1e6', shortcode: ':ca:', category: 'flags' },
  { id: '1f1eb-1f1f7', name: 'France', unicode: '1f1eb-1f1f7', shortcode: ':fr:', category: 'flags' },
  { id: '1f1ec-1f1e7', name: 'United Kingdom', unicode: '1f1ec-1f1e7', shortcode: ':gb:', category: 'flags' },
  { id: '1f1fa-1f1f8', name: 'United States', unicode: '1f1fa-1f1f8', shortcode: ':us:', category: 'flags' },
  { id: '1f1ef-1f1f5', name: 'Japan', unicode: '1f1ef-1f1f5', shortcode: ':jp:', category: 'flags' },
  { id: '1f1e9-1f1ea', name: 'Germany', unicode: '1f1e9-1f1ea', shortcode: ':de:', category: 'flags' },
];
